// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_YUn10DJhrkhvYvnY5UAavrvKfqfYlgc',
    appId: '1:652369610091:web:a5324f57f0d791d05d782e',
    messagingSenderId: '652369610091',
    projectId: 'playhub-9cd5a',
    authDomain: 'playhub-9cd5a.firebaseapp.com',
    storageBucket: 'playhub-9cd5a.firebasestorage.app',
    measurementId: 'G-FF9DLFV4W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChifT4h6oYw35rRHvhd1asx5s94lVpEmc',
    appId: '1:652369610091:android:6c3117b2f78e33fd5d782e',
    messagingSenderId: '652369610091',
    projectId: 'playhub-9cd5a',
    storageBucket: 'playhub-9cd5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSbLM8faiVzxh7jZ5bf_bVfmrxn3ENnqI',
    appId: '1:652369610091:ios:af610b802c8dcb305d782e',
    messagingSenderId: '652369610091',
    projectId: 'playhub-9cd5a',
    storageBucket: 'playhub-9cd5a.firebasestorage.app',
    iosBundleId: 'com.example.game',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSbLM8faiVzxh7jZ5bf_bVfmrxn3ENnqI',
    appId: '1:652369610091:ios:af610b802c8dcb305d782e',
    messagingSenderId: '652369610091',
    projectId: 'playhub-9cd5a',
    storageBucket: 'playhub-9cd5a.firebasestorage.app',
    iosBundleId: 'com.example.game',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_YUn10DJhrkhvYvnY5UAavrvKfqfYlgc',
    appId: '1:652369610091:web:d4fc552401878e835d782e',
    messagingSenderId: '652369610091',
    projectId: 'playhub-9cd5a',
    authDomain: 'playhub-9cd5a.firebaseapp.com',
    storageBucket: 'playhub-9cd5a.firebasestorage.app',
    measurementId: 'G-ED0W1JWC9E',
  );
}
